(version 1)
(deny default)
(allow file-read* (subpath "{{ pwd }}"))
(allow file-write* (subpath "{{ pwd }}"))
(allow file-read* (subpath "/usr/lib"))
(allow file-read* (subpath "/System"))
(allow file-read-metadata)
(allow file-map-executable)
(allow mach-lookup)
(allow sysctl-read)
