{% include "node" %}
(allow file-read* (subpath "{{ home }}/.claude"))
(allow file-read* (prefix "{{ home }}/.claude.json"))
(allow file-read* (subpath "{{ home }}/.local/share/claude"))
(allow file-read* (subpath "{{ home }}/.local/state/claude"))
(allow file-read* (subpath "{{ home }}/.cache/claude"))
(allow file-read* (subpath "{{ home }}/Library/Caches/claude-cli-nodejs"))
(allow file-read* (subpath "{{ home }}/Library/Keychains"))
(allow file-write* (subpath "{{ home }}/Library/Keychains"))
(allow file-write* (subpath "{{ home }}/.claude"))
(allow file-write* (prefix "{{ home }}/.claude.json"))
(allow file-write* (subpath "{{ home }}/.local/state/claude"))
(allow file-write* (subpath "{{ home }}/.cache/claude"))
