(version 1)
(deny default)
(allow file-read* (subpath "{{ pwd }}"))
(allow file-write* (subpath "{{ pwd }}"))
(allow file-read* (subpath "{{ home }}"))
(deny file-read* (subpath "{{ home }}/.ssh"))
(deny file-read* (subpath "{{ home }}/.gnupg"))
(deny file-read* (subpath "{{ home }}/.aws"))
(deny file-read* (subpath "{{ home }}/.docker"))
(deny file-read* (subpath "{{ home }}/.kube"))
(deny file-read* (subpath "{{ home }}/.config/gh"))
(deny file-read* (subpath "{{ home }}/.password-store"))
(deny file-read* (literal "{{ home }}/.netrc"))
(deny file-read* (literal "{{ home }}/.bash_history"))
(deny file-read* (literal "{{ home }}/.zsh_history"))
(deny file-read* (literal "{{ home }}/.history"))
(deny file-read* (literal "{{ home }}/.npmrc"))
(deny file-read* (literal "{{ home }}/.cargo/credentials.toml"))
(deny file-read* (subpath "{{ home }}/Library/Keychains"))
(deny file-read* (subpath "{{ home }}/Library/Mail"))
(deny file-read* (subpath "{{ home }}/Library/Messages"))
(deny file-read* (subpath "{{ home }}/Library/Cookies"))
(allow file-read* (subpath "/usr/lib"))
(allow file-read* (subpath "/usr/share"))
(allow file-read* (subpath "/System"))
(allow file-read* (subpath "/etc"))
(allow file-read* (subpath "/private/etc"))
(allow file-read* (subpath "/dev"))
(allow file-write* (subpath "/dev"))
(allow file-ioctl)
(allow file-read-metadata)
(allow file-map-executable)
(allow mach-lookup)
(allow sysctl-read)
(allow ipc-posix-shm)
(allow signal)
(allow network-outbound)
(allow process-exec)
(allow process-fork)
{% for dir in path %}
(allow file-read* (subpath "{{ dir }}"))
{% endfor %}
