(version 1)
(deny default)
(allow file-read* (subpath "{{ pwd }}"))
(allow file-write* (subpath "{{ pwd }}"))
(allow file-read* (literal "{{ home }}/.CFUserTextEncoding"))
(allow file-read* (literal "/"))
(allow file-read* (subpath "/Library"))
(allow file-read* (subpath "/opt"))
(allow file-read* (subpath "/usr/lib"))
(allow file-read* (subpath "/usr/share"))
(allow file-read* (subpath "/System"))
(allow file-read* (subpath "/etc"))
(allow file-read* (subpath "/private"))
(allow file-read* (subpath "/dev"))
(allow file-write* (subpath "/dev"))
(allow file-write* (subpath "/private/var/folders"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "{{ home }}/Library/Caches"))
(allow file-ioctl)
(allow file-read-metadata)
(allow file-map-executable)
(allow mach-lookup)
(allow sysctl-read)
(allow ipc-posix-shm)
(allow signal)
(allow network-outbound)
(allow process-exec)
(allow process-fork)
(allow system-socket)
{% for dir in path %}
(allow file-read* (subpath "{{ dir }}"))
{% endfor %}
(allow file-read* (literal "{{ home }}/.gitconfig"))
(allow file-read* (subpath "{{ home }}/.config/git"))
(allow file-read* (literal "{{ home }}/.npmrc"))
(allow file-read* (subpath "{{ home }}/.npm"))
(allow file-write* (subpath "{{ home }}/.npm"))
(allow file-read* (literal "{{ home }}/.node_repl_history"))
(allow file-write* (literal "{{ home }}/.node_repl_history"))
